// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyl9tQB_B6u3SuluSDDViCfjXA5zVH7gc',
    appId: '1:14033851779:android:a0b1d92e0f94e3a64892b6',
    messagingSenderId: '14033851779',
    projectId: 'chat-5114c',
    databaseURL: 'https://chat-5114c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-5114c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BgSwhHEhqXCBhoqBARt1IJk2YRpKzrY',
    appId: '1:14033851779:ios:86df8bece08fb12d4892b6',
    messagingSenderId: '14033851779',
    projectId: 'chat-5114c',
    databaseURL: 'https://chat-5114c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-5114c.firebasestorage.app',
    androidClientId: '14033851779-4m2c8g1onc3cf76akljh5q4abp4f4r0o.apps.googleusercontent.com',
    iosClientId: '14033851779-sr0tr614pndgil6dcasiu7eud4b3ir0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nourMarket2',
  );
}
